# Generated by Django 4.2.6 on 2023-10-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('located_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pet_pics/')),
                ('age', models.IntegerField(max_length=30)),
                ('build', models.PositiveSmallIntegerField(choices=[(1, 'Porte pequeno'), (2, 'Porte médio'), (3, 'Porte Grande')], verbose_name='Role')),
                ('short_description', models.CharField(blank=True, max_length=155, null=True)),
                ('located_at', models.CharField(max_length=255)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.shelter')),
            ],
        ),
    ]
