# Generated by Django 4.2.6 on 2023-10-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_tutor'),
        ('pet', '0003_pet_adopted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='account.tutor'),
        ),
    ]
